---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ovh-nasha-operator
  namespace: "kube-system"
  labels:
    app.kubernetes.io/name: ovh-nasha-operator
    app.kubernetes.io/instance: ovh-nashha-operator
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ovh-nasha-operator
    app.kubernetes.io/instance: ovh-nashha-operator
  name: ovh-nasha-operator
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ovh-nasha-operator
    app.kubernetes.io/instance: ovh-nashha-operator
  name: ovh-nasha-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ovh-nasha-operator
subjects:
  - kind: ServiceAccount
    name: ovh-nasha-operator
    namespace: "kube-system"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: ovh-nasha-operator
    app.kubernetes.io/instance: ovh-nashha-operator
  name: ovh-nasha-operator
  namespace: "kube-system"
rules:
  - apiGroups:
      - ""
    resourceNames:
      - ovh-nasha
    resources:
      - configmaps
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ovh-nasha-operator
    app.kubernetes.io/instance: ovh-nashha-operator
  name: ovh-nasha-operator
  namespace: "kube-system"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ovh-nasha-operator
subjects:
  - kind: ServiceAccount
    name: ovh-nasha-operator
    namespace: "kube-system"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: ovh-nasha-operator
    app.kubernetes.io/instance: ovh-nashha-operator
    app.kubernetes.io/component: controller
  name: ovh-nasha-operator
  namespace: "kube-system"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ovh-nasha-operator
      app.kubernetes.io/instance: ovh-nashha-operator
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ovh-nasha-operator
        app.kubernetes.io/instance: ovh-nashha-operator
        app.kubernetes.io/component: controller
    spec:
      containers:
        - name: ovh-nasha-operator
          image: vixns/ovh-nasha-operator
          resources:
            limits:
              memory: 64Mi
            requests:
              cpu: 5m
              memory: 32Mi
          volumeMounts:
            - name: ovh-nasha
              mountPath: "/nasha.json"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: OVH_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: nasha-ovh.conf
                  key: endpoint
            - name: OVH_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: nasha-ovh.conf
                  key: consumer
            - name: OVH_APPLICATION_KEY
              valueFrom:
                secretKeyRef:
                  name: nasha-ovh.conf
                  key: key
            - name: OVH_APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: nasha-ovh.conf
                  key: secret
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: ovh-nasha
          configMap:
            name: ovh-nasha
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ovh-nasha-operator
      serviceAccountName: ovh-nasha-operator
      terminationGracePeriodSeconds: 30
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
