{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "ovh-nasha-operator.labels" . | nindent 4 }}
  name: {{ include "ovh-nasha-operator.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
{{- end }}
