{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "ovh-nasha-operator.labels" . | nindent 4 }}
  name: {{ include "ovh-nasha-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ovh-nasha-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "ovh-nasha-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
