apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "ovh-nasha-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
  name: {{ include "ovh-nasha-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      {{- include "ovh-nasha-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        {{- include "ovh-nasha-operator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: operator
    spec:
      containers:
        - name: {{ include "ovh-nasha-operator.fullname" . }}
          image: {{ .Values.image.name }}
          command: 
            - /ovh-nasha-operator
          resources:
            limits:
              memory: 64Mi
            requests:
              cpu: 5m
              memory: 32Mi
          env:
            - name: OVH_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ovh.api.secretName }}
                  key: endpoint
            - name: OVH_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ovh.api.secretName }}
                  key: consumer_key
            - name: OVH_APPLICATION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ovh.api.secretName }}
                  key: application_key
            - name: OVH_APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ovh.api.secretName }}
                  key: application_secret
            - name: LOG_LEVEL
              value: {{ .Values.loglevel }}
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: {{ template "ovh-nasha-operator.serviceAccountName" . }}
      serviceAccountName: {{ template "ovh-nasha-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
