{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "ovh-nasha-operator.labels" . | nindent 4 }}
  name: {{ include "ovh-nasha-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  {{ include "ovh-nasha-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name:  {{ template "ovh-nasha-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
