apiVersion: v1
data:
  endpoint: {{ .Values.ovh.api.token.endpoint | b64enc }}
  key: {{ .Values.ovh.api.token.application_key | b64enc }}
  secret: {{ .Values.ovh.api.token.application_secret |b64enc }}
  consumer: {{ .Values.ovh.api.token.consumer_key |b64enc }}
kind: Secret
metadata:
  name: nasha-ovh.conf
